'use client';

import { motion, useReducedMotion } from 'framer-motion';
import { Spotlight } from '../ui/spotlight';
import { HoverBorderGradient } from '../ui/hover-border-gradient';
import { ShootingStars } from '../ui/shooting-stars';
import { StarsBackground } from '../ui/stars-background';
import { PipelineGraph } from './PipelineGraph';
import { GradualSpacing } from '../ui/gradual-spacing';
import { TextBlurFade } from '../ui/text-blur-fade';

const fadeUp = {
  hidden: { opacity: 0, y: 16 },
  visible: { opacity: 1, y: 0 },
};

export function Hero({ loginUrl }: { loginUrl: string }) {
  const reduceMotion = useReducedMotion();

  return (
    <section
      className="relative overflow-hidden pt-20 pb-8 text-center"
      id="top"
    >
      {/* dot grid backdrop */}
      <div
        className="pointer-events-none absolute inset-0 bg-[radial-gradient(rgba(255,255,255,0.06)_1px,transparent_1px)] bg-size-[28px_28px] mask-[radial-gradient(ellipse_60%_55%_at_50%_35%,black,transparent)]"
        aria-hidden="true"
      />
      <StarsBackground
        className="pointer-events-none"
        starDensity={0.0002}
        allStarsTwinkle={!reduceMotion}
        twinkleProbability={reduceMotion ? 0 : 0.7}
      />
      {!reduceMotion && (
        <>
          <ShootingStars
            className="pointer-events-none"
            starColor="#5b8def"
            trailColor="#8b5cf6"
            minDelay={1800}
            maxDelay={4600}
          />
          <ShootingStars
            className="pointer-events-none"
            starColor="#2dd4bf"
            trailColor="#5b8def"
            minDelay={3200}
            maxDelay={7200}
          />
        </>
      )}
      <Spotlight className="-top-40 left-0 md:-top-20 md:left-60" fill="#5b8def" />

      <div className="relative z-10 mx-auto max-w-290 px-6">
        <motion.span
          className="eyebrow"
          initial={reduceMotion ? 'visible' : 'hidden'}
          animate="visible"
          variants={fadeUp}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          <span className="h-1.5 w-1.5 rounded-full bg-glow-teal" aria-hidden="true" />
          Multi-agent code analysis
        </motion.span>

        <motion.h1
          className={`mx-auto mt-0 mb-4 max-w-5xl text-5xl font-extrabold tracking-tight md:text-[5rem] md:leading-[1.04] ${
            reduceMotion
              ? 'bg-linear-to-b from-white via-white to-white/55 bg-clip-text text-transparent'
              : 'text-white'
          }`}
          initial={reduceMotion ? 'visible' : 'hidden'}
          animate="visible"
          variants={fadeUp}
          transition={{ duration: 0.8, delay: 0.05, ease: [0.16, 1, 0.3, 1] }}
        >
          {reduceMotion ? (
            <>
              Understand any codebase
              <br />
              before you touch it.
            </>
          ) : (
            <GradualSpacing
              text={'Understand any codebase\nbefore you touch it.'}
              className="bg-linear-to-b from-white via-white to-white/55 bg-clip-text text-transparent"
              duration={0.8}
              staggerDelay={0.06}
            />
          )}
        </motion.h1>

        <p className="mx-auto mt-0 mb-8 max-w-xl text-[1.375rem] leading-relaxed">
          <TextBlurFade
            text="Point CodeMind at a repo and get architecture, security, dependency, quality, and docs reports back — generated by agents that actually read the code."
            delay={0.25}
            duration={0.8}
            staggerDelay={0.025}
          />
        </p>

        <motion.div
          className="flex flex-wrap items-center justify-center gap-4"
          initial={reduceMotion ? 'visible' : 'hidden'}
          animate="visible"
          variants={fadeUp}
          transition={{ duration: 0.8, delay: 0.35, ease: [0.16, 1, 0.3, 1] }}
        >
          <HoverBorderGradient
            as="a"
            containerClassName="rounded-full no-underline"
            className="bg-bg px-6 py-2.5 text-[0.9375rem] font-semibold text-white"
            {...{ href: loginUrl }}
          >
            Connect GitHub
          </HoverBorderGradient>
          <a className="btn btn-secondary" href="#reports">
            See a sample report
          </a>
        </motion.div>

        <motion.div
          className="mt-14"
          initial={reduceMotion ? 'visible' : { opacity: 0, y: 24 }}
          animate="visible"
          variants={{ visible: { opacity: 1, y: 0 } }}
          transition={{ duration: 1.2, delay: 0.5, ease: [0.16, 1, 0.3, 1] }}
        >
          <PipelineGraph />
        </motion.div>
      </div>
    </section>
  );
}
